database:
  type: 'mysql'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: '1234'
  database: 'db_auth'
  timezone: 'Z'
  autoLoadEntities: true
  maxQueryExecutionTime: 1000
  synchronize: true
  logging: true
