database:
  type: 'mysql'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'SuperTree!@#$7890'
  database: 'db_auth'
  timezone: 'Z'
  entities: ['dist/**/*.entity.{ts,js}']
  maxQueryExecutionTime: 1000
  synchronize: true
  logging: true
