database:
  type: 'mysql'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'SuperTree!@#$7890'
  timezone: 'Z' # UTC
  autoLoadEntities: true
  maxQueryExecutionTime: 1000 # log for long query 
  synchronize: false
  logging: true 
